apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-flex-nfs
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    flexVolume:
        driver: 'k8s/nfs'
        fsType: 'nfs'
        options:
            server: '10.10.0.25' # 改成你自己的NFS服务器地址
            share: 'export'
