apiVersion: batch/v1
kind: Job
metadata:
    name: pi
spec:
    # batch
    parallelism: 2
    completions: 4
    template:
        spec:
            containers:
                - name: pi
                  image: resouer/ubuntu-bc
                  # a(1) 是调用数学库中的 arctangent 函数，计算 atan(1)
                  command: ['sh', '-c', "echo 'scale=10000; 4*a(1)' | bc -l "]
            restartPolicy: Never
    backoffLimit: 4
