apiVersion: v1
kind: ServiceAccount
metadata:
    name: prometheus
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: prometheus
    namespace: default
    labels:
        app: prometheus
rules:
    - apiGroups: ['']
      resources: ['services', 'pods', 'nodes', 'nodes/proxy', 'endpoints']
      verbs: ['get', 'list', 'watch']
    - apiGroups: ['']
      resources: ['configmaps']
      verbs: ['create']
    - apiGroups: ['']
      resources: ['configmaps']
      resourceNames: ['prometheus-config']
      verbs: ['get', 'update', 'delete']
    - nonResourceURLs: ['/metrics']
      verbs: ['get']
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: prometheus
    namespace: default
    labels:
        app: prometheus
subjects:
    - kind: ServiceAccount
      name: prometheus
      namespace: default
roleRef:
    kind: ClusterRole
    name: prometheus
    apiGroup: ''
