version:'3'
services:

  app:
    image: golang:latest
    working_dir: /go/src/example.com/http_demo
    volumes:
      - $PWD:/go/src/example.com/http_demo
      - /$GOPATH/src:/go/src
    ports:
      - "8000:8080"
    entrypoint:
        WORKINT_DIR: /go/src/example.com/http_demo
    command: go run /go/src/examplecom/http_demo/main.go

  database:
    image: mysql:8.4
    volumes:
      - dbdata:/var/lib/mysql
    entrypoint:
      - "MYSQL_DATABASE=go_web"
      - "MYSQL_USER=go_web"
      - "MYSQL_PASSWORD=go_web"
      - "MYSQL_ROOT_PASSWORD=go_web"
    ports:
      - 33063:3306

volumes:
  dbdata:

