version: "3.6"

services:
  redis-master1:
     image: redis # 基础镜像
     container_name: redis-master1 # 容器服务名
     working_dir: /config # 工作目录
     environment: # 环境变量
       - PORT=7000 # 跟 config/nodes-6391.conf 里的配置一样的端口
     ports: # 映射端口，对外提供服务
       - "7000:6391" # redis 的服务端口
       - "16391:16391" # redis 集群监控端口
     stdin_open: true # 标准输入打开
     networks: # docker 网络设置
        redis-master:
            ipv4_address: 172.50.0.2
     tty: true
     privileged: true # 拥有容器内命令执行的权限
     volumes:
		- $PWD/7000/data:/data
		- $PWD/7000/redis.conf:/etc/redis/redis.conf # 映射数据卷，配置目录
     entrypoint: # 设置服务默认的启动程序
       - /bin/bash
	   - redis.sh

  redis-master2:
       image: redis
       working_dir: /config
       container_name: redis-master2
       environment:
              - PORT=7001
       networks:
          redis-master:
             ipv4_address: 172.50.0.3
       ports:
         - "7001:6392"
         - "16392:16392"
       stdin_open: true
       tty: true
       privileged: true
       volumes:
         - $PWD/7001/data:/data
		 - $PWD/7001/redis.conf:/etc/redis/redis.conf  # 映射数据卷，配置目
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-master3:
       image: redis
       container_name: redis-master3
       working_dir: /config
       environment:
              - PORT=7003
       networks:
          redis-master:
            ipv4_address: 172.50.0.4
       ports:
         - "7003:6393"
         - "16393:16393"
       stdin_open: true
       tty: true
       privileged: true
       volumes:
		- $PWD/7003/data:/data
		- $PWD/7003/redis.conf:/etc/redis/redis.conf  # 映射数据卷，配置目
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-slave1:
       image: redis
       container_name: redis-slave1
       working_dir: /config
       environment:
            - PORT=7003
       networks:
          redis-slave:
             ipv4_address: 172.30.0.2
       ports:
         - "7004:6394"
         - "16394:16394"
       stdin_open: true
       tty: true
       privileged: true
     volumes:
		- $PWD/7004/data:/data
		- $PWD/7004/redis.conf:/etc/redis/redis.conf  # 映射数据卷，配置目
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-salve2:
       image: redis
       working_dir: /config
       container_name: redis-salve2
       environment:
             - PORT=7005
       ports:
         - "7005:6395"
         - "16395:16395"
       stdin_open: true
       networks:
          redis-slave:
              ipv4_address: 172.30.0.3
       tty: true
       privileged: true
     volumes:
		- $PWD/7000/data:/data
		- $PWD/7005/redis.conf:/etc/redis/redis.conf
       entrypoint:
         - /bin/bash
         - redis.sh
  redis-salve3:
       image: redis
       container_name: redis-slave3
       working_dir: /config
       environment:
          - PORT=7006
       ports:
         - "7006:6396"
         - "16396:16396"
       stdin_open: true
       networks:
          redis-slave:
            ipv4_address: 172.30.0.4
       tty: true
       privileged: true
     volumes:
		- $PWD/7006/data:/data
		- $PWD/7006/redis.conf:/etc/redis/redis.conf 目
       entrypoint:
         - /bin/bash
         - redis.sh

networks:
  redis-master:
     driver: bridge # 创建一个docker 的桥接网络
     ipam:
       driver: default
       config:
          -
           subnet: 172.50.0.0/16

  redis-slave:
       driver: bridge
       ipam:
         driver: default
         config:
            -
             subnet: 172.30.0.0/16
