apiVersion: apps/v1
kind: Deployment
metadata:
    name: nginx-deployment
spec:
    selector:
        matchLabels:
            app: nginx
    replicas: 2
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 1
            maxUnavailable: 50%
    template:
        metadata:
            labels:
                app: nginx
        spec:
            containers:
                - name: nginx
                  image: nginx:1.25
                  ports:
                      - containerPort: 8081
                  volumeMounts:
                      - mountPath: '/usr/share/nginx/html'
                        name: nginx-vol
            volumes:
                - name: nginx-vol
                  # emptyDir: {}
                  hostPath:
                      path: '/Users/henry/Workspace/Code/basic/html/HTML5'
