apiVersion: apps/v1
kind: Deployment
metadata:
    name: myapp
    namespace: myns
spec:
    replicas: 2
    selector:
        matchLabels:
            app: myapp
            rel: beta
    template:
        metadata:
            namespace: myns
            labels:
                app: myapp
                rel: beta
        spec:
            containers:
                - name: myapp
                  image: ikubernetes/myapp:v1

---
apiVersion: v1
kind: Service
metadata:
    name: myapp
    namespace: myns
spec:
    # 配置会话黏性
    sessionAffinity: ClientIP
    selector:
        app: myapp
        rel: beta
    ports:
        - name: http
          port: 80
          targetPort: 80
